# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18YBxGZu4KrR9NuFcYW4Yz09cWK4yDndL
"""

count = 0
nhap = input("Nhập lựa chọn: ")
strr = ""
for x in nhap:
  if x == "w":
    if i == "a" or i =="o":
      count +=1
      strr += i + x + ", "
    else:
      count +=1
      strr += x + ", "
  if x == "a":
    if i == "a":
      count +=1
      strr += i + x + ", "
  if x == "d":
    if i == "d":
      count +=1
      strr += i + x + ", "
  if x == "e":
    if i == "e":
      count +=1
      strr += i + x + ", "
  if x == "o":
    if i == "o":
      count +=1
      strr += i + x + ", "
  i = x
print(count)
print(strr)